# Generated by Django 4.2.1 on 2023-06-23 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
