# Generated by Django 4.2.1 on 2023-06-24 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title']},
        ),
    ]
